---
driver:
  name: vagrant
  require_chef_omnibus: 12.13.37
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[centos-lamp::default]
    attributes:
      centos-lamp:
        database:
          root_password: 'mysql_root_password'
          admin_password: 'mysql_admin_password'
